### ISSUE TITLE
Mistake in entrypoint.sh

### ISSUE THREAD

**Issue by mdorofeev** [tonlabs/rustnet.ton.dev#1]
Rust node can't start, as in entrypoint .sh mistake on line 43, it try change mod in tools directory, but file in scripts directory.

https://github.com/tonlabs/rustnet.ton.dev/blob/075b53a0c896d36a53cc9d349e7f08fda61eb645/docker-compose/ton-node/scripts/entrypoint.sh#L43

**Comment by duccas** [comment]
I confirm.
Error in docker logs:
```
Reading package lists...
Building dependency tree...
Reading state information...
cron is already the newest version (3.0pl1-128.1ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
+ grep 'validator_msig\|validator_depool' /etc/crontab
+ chmod +x /ton-node/tools/validator_msig.sh
chmod: cannot access '/ton-node/tools/validator_msig.sh': No such file or directory
```
The files is located in a folder with a different name `find ./rustnet.ton.dev -type f -name "validator_msig.sh"`
```
./rustnet.ton.dev/docker-compose/ton-node/scripts/validator_msig.sh
```

![image](https://user-images.githubusercontent.com/64695363/104816002-48032080-5829-11eb-86c9-f6d117978ce1.png)

**Comment by ar-tmp** [comment]
Fixed, thanks.
