### ISSUE TITLE
Can't update node with latest master

### ISSUE THREAD

**Issue by slavaschmidt** [tonlabs/rustnet.ton.dev#10]
The update process fails with following error message: `Can't generate console_config.json: delete config.json before`

And then later: `ERROR: /ton-node/configs/console_config.json does not exist`

**Comment by ar-tmp** [comment]
If you would like to start a new node please cleanup files in your git tree and restart the deployment according to the README procedure.

**Comment by ar-tmp** [comment]
You can find detailed instructions here: https://docs.ton.dev/86757ecb2/p/7991ca-run-rust-validator
Please re-open the issue if it is still actual.

**Comment by simmon-nplob** [comment]
also, I'm same issue, how to resolve the problem?
'ERROR: /ton-node/configs/console_config.json does not exist'

**Comment by simmon-nplob** [comment]
Logging - During deployment
I don't think it's necessary to do that execution over and over again.
