### ISSUE TITLE
Optimize script suggestions

### ISSUE THREAD

**Issue by engaiX** [tonlabs/rustnet.ton.dev#14]
I suggest to modify the rust version to 1.53.0
rustnet.ton.dev/docker-compose/ton-node/build/Dockerfile

ARG RUST_VERSION=1.53.0

Because after installing it several times, I found that 1.51.0 will freeze for more than ten minutes in the following steps.
The 1.53.0 version will not freeze,
Although I don't know the specific reason. However, this modification can save installation time.

![image](https://user-images.githubusercontent.com/33893148/130165132-f5d9b224-9da5-4426-9027-3536c146295a.png)

**Comment by engaiX** [comment]
Such a modification will quickly proceed to the next step,
Optimize the deployment script time.
![image](https://user-images.githubusercontent.com/33893148/130166371-0f146a0c-5410-40f7-863d-af6e9952118f.png)

**Comment by ar-tmp** [comment]
RUST is updated to 1.55.0
