### ISSUE TITLE
change in env.sh *_GITHUB_REPO="git@github.com: ssh to https 

### ISSUE THREAD

**Issue by casper-ru** [tonlabs/rustnet.ton.dev#2]
export TON_NODE_GITHUB_REPO="https://github.com/tonlabs/ton-labs-node.git"
export TON_NODE_TOOLS_GITHUB_REPO="https://github.com/tonlabs/ton-labs-node-tools.git"
export TONOS_CLI_GITHUB_REPO="https://github.com/tonlabs/tonos-cli.git"

**Comment by ar-tmp** [comment]
Fixed, thanks.
