### ISSUE TITLE
ERROR: Service 'node' failed to build  Сode: 101

### ISSUE THREAD

**Issue by roma4u** [tonlabs/rustnet.ton.dev#4]
On a clean system, I get the following error:

```
Step 15/29 : RUN cargo update && cargo build --release
 ---> Running in 49d5d124dcdb
error: current package believes it's in a workspace when it's not:
current:   /tonlabs/ton-node/ton-labs-node-tools/Cargo.toml
workspace: /tonlabs/ton-node/Cargo.toml

this may be fixable by adding `ton-labs-node-tools` to the `workspace.members` array of the manifest located at: /tonlabs/ton-node/Cargo.toml
Alternatively, to keep it out of the workspace, add the package to the `workspace.exclude` array, or add an empty `[workspace]` table to the package's manifest.
ERROR: Service 'node' failed to build: The command '/bin/sh -c cargo update && cargo build --release' returned a non-zero code: 101
root@TESTVAL ~/rustnet.ton.dev/scripts # 
```

**Comment by stakrspace** [comment]
Compiling ton_node v0.1.0 (/tonlabs/ton-node)
warning: function is never used: `construct_from_file`
   --> src/collator_test_bundle.rs:140:4
    |
140 | fn construct_from_file<T: Deserializable>(path: &str) -> Result<(T, UInt256, UInt256)> {
    |    ^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(dead_code)]` on by default

warning: associated function is never used: `build_with_zero_state`
   --> src/collator_test_bundle.rs:164:18
    |
164 |     pub async fn build_with_zero_state(mc_zero_state_name: &str, wc_zero_state_name: &str) -> Result<Self> {
    |                  ^^^^^^^^^^^^^^^^^^^^^

warning: associated function is never used: `load`
   --> src/collator_test_bundle.rs:804:12
    |
804 |     pub fn load(path: &str) -> Result<Self> {
    |            ^^^^

warning: associated function is never used: `ethalon_block`
   --> src/collator_test_bundle.rs:951:12
    |
951 |     pub fn ethalon_block(&self) -> Result<Option<BlockStuff>> {
    |            ^^^^^^^^^^^^^

warning: associated function is never used: `block_id`
   --> src/collator_test_bundle.rs:990:12
    |
990 |     pub fn block_id(&self) -> &BlockIdExt { &self.index.id }
    |            ^^^^^^^^

warning: associated function is never used: `prev_blocks_ids`
   --> src/collator_test_bundle.rs:991:12
    |
991 |     pub fn prev_blocks_ids(&self) -> &Vec<BlockIdExt> { &self.index.prev_blocks }
    |            ^^^^^^^^^^^^^^^

warning: associated function is never used: `min_ref_mc_seqno`
   --> src/collator_test_bundle.rs:992:12
    |
992 |     pub fn min_ref_mc_seqno(&self) -> u32 { self.index.min_ref_mc_seqno }
    |            ^^^^^^^^^^^^^^^^

warning: associated function is never used: `created_by`
   --> src/collator_test_bundle.rs:993:12
    |
993 |     pub fn created_by(&self) -> &UInt256 { &self.index.created_by }
    |            ^^^^^^^^^^

warning: associated function is never used: `rand_seed`
   --> src/collator_test_bundle.rs:994:12
    |
994 |     pub fn rand_seed(&self) -> Option<&UInt256> { self.index.rand_seed.as_ref() }
    |            ^^^^^^^^^

warning: associated function is never used: `notes`
   --> src/collator_test_bundle.rs:996:12
    |
996 |     pub fn notes(&self) -> &str { &self.index.notes }
    |            ^^^^^

warning: function is never used: `message_from_kafka_received`
  --> src/main.rs:29:12
   |
29 |     pub fn message_from_kafka_received(_kf_key: &[u8]) {}
   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: 11 warnings emitted

    Finished release [optimized] target(s) in 3m 24s
Removing intermediate container 6fd3b594d5d3
 ---> 17e667dae09f
Step 14/29 : WORKDIR /tonlabs/ton-node/ton-labs-node-tools
 ---> Running in ec99f590f061
Removing intermediate container ec99f590f061
 ---> 34a8bb2e2bb1
Step 15/29 : RUN cargo update && cargo build --release
 ---> Running in 25aa2e5422d1
error: current package believes it's in a workspace when it's not:
current:   /tonlabs/ton-node/ton-labs-node-tools/Cargo.toml
workspace: /tonlabs/ton-node/Cargo.toml

this may be fixable by adding `ton-labs-node-tools` to the `workspace.members` array of the manifest located at: /tonlabs/ton-node/Cargo.toml
Alternatively, to keep it out of the workspace, add the package to the `workspace.exclude` array, or add an empty `[workspace]` table to the package's manifest.
ERROR: Service 'node' failed to build: The command '/bin/sh -c cargo update && cargo build --release' returned a non-zero code: 101

**Comment by engaiX** [comment]
me too
arning: 11 warnings emitted

    Finished release [optimized] target(s) in 8m 32s
Removing intermediate container 8f7405d4f33c
 ---> 93eb41f522d8
Step 14/29 : WORKDIR /tonlabs/ton-node/ton-labs-node-tools
 ---> Running in c3aed7870ace
Removing intermediate container c3aed7870ace
 ---> db374f412c0f
Step 15/29 : RUN cargo update && cargo build --release
 ---> Running in 4079cedddbd9
error: current package believes it's in a workspace when it's not:
current:   /tonlabs/ton-node/ton-labs-node-tools/Cargo.toml
workspace: /tonlabs/ton-node/Cargo.toml

this may be fixable by adding `ton-labs-node-tools` to the `workspace.members` array of the manifest located at: /tonlabs/ton-node/Cargo.toml
Alternatively, to keep it out of the workspace, add the package to the `workspace.exclude` array, or add an empty `[workspace]` table to the package's manifest.
ERROR: Service 'node' failed to build: The command '/bin/sh -c cargo update && cargo build --release' returned a non-zero code: 101

**Comment by roma4u** [comment]
Guys suggested this:
```
git clone https://github.com/tonlabs/rustnet.ton.dev.git
git checkout artemr/depool_support
./deploy.sh 
# docker ps
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS                    PORTS                                        NAMES
1ea33bf65671        ton-node_node                  "/ton-node/scripts/e…"   11 minutes ago      Up 11 minutes             0.0.0.0:30303->30303/udp                     rnode
72dd5da994d8        prom/statsd-exporter:v0.12.2   "/bin/statsd_exporte…"   23 minutes ago      Up 23 minutes (healthy)   0.0.0.0:9102->9102/tcp, 9125/tcp, 9125/udp   statsd
```

**Comment by stakrspace** [comment]
> Guys suggested this:
> 
> ```
> git clone https://github.com/tonlabs/rustnet.ton.dev.git
> git checkout artemr/depool_support
> ./deploy.sh 
> # docker ps
> CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS                    PORTS                                        NAMES
> 1ea33bf65671        ton-node_node                  "/ton-node/scripts/e…"   11 minutes ago      Up 11 minutes             0.0.0.0:30303->30303/udp                     rnode
> 72dd5da994d8        prom/statsd-exporter:v0.12.2   "/bin/statsd_exporte…"   23 minutes ago      Up 23 minutes (healthy)   0.0.0.0:9102->9102/tcp, 9125/tcp, 9125/udp   statsd
> ```

Thanks, worked out

**Comment by ar-tmp** [comment]
Thanks for reporting, fixed (available in master).
