### ISSUE TITLE
Error line 238 in validator.sh

### ISSUE THREAD

**Issue by stakrspace** [tonlabs/rustnet.ton.dev#8]
+ prepare_for_elections
+ case ${ELECTOR_TYPE} in
++ /ton-node/tools/tonos-cli run -1:3333333333333333333333333333333333333333333333333333333333333333 active_election_id '{}' --abi /ton-node/configs/Elector.abi.json
++ grep value0
++ awk '{print $2}'
++ tr -d '"'
thread 'main' panicked at 'a parsed Url should always be a valid Uri: InvalidUri(InvalidUriChar)', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.10/src/into_url.rs:42:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
+++ exit_and_clean 1 238
+++ EXIT_CODE=1
+++ EXIT_LINE=238
+++ rm -f /tmp/validator.lock
+++ '[' 1 -eq 0 ']'
+++ echo 'INFO: script exited (exit code: 1, script line: 238)'
++++ basename ./validator.sh
++++ date +%s
++++ date
+++ echo 'INFO: validator.sh END 1613338563 / Sun Feb 14 21:36:03 UTC 2021'
+++ exit 1
+ ACTIVE_ELECTION_ID_HEX='INFO: script exited (exit code: 1, script line: 238)
INFO: validator.sh END 1613338563 / Sun Feb 14 21:36:03 UTC 2021'
++ exit_and_clean 1 238
++ EXIT_CODE=1
++ EXIT_LINE=238
++ rm -f /tmp/validator.lock
++ '[' 1 -eq 0 ']'
++ echo 'INFO: script exited (exit code: 1, script line: 238)'
INFO: script exited (exit code: 1, script line: 238)
+++ basename ./validator.sh
+++ date +%s
+++ date
++ echo 'INFO: validator.sh END 1613338563 / Sun Feb 14 21:36:03 UTC 2021'
INFO: validator.sh END 1613338563 / Sun Feb 14 21:36:03 UTC 2021

**Comment by ar-tmp** [comment]
Could you please show your tonos-cli config?

**Comment by stakrspace** [comment]
> Could you please show your tonos-cli config?

looks like it puts wrong slash after rustnet.ton.dev running from the validator script:

+ /ton-node/tools/tonos-cli config --url '"https://rustnet.ton.dev"' --retries 5 --addr 0:878b80596139958f45b3ce3e75211c2620b568d203ce382e7baf8fa4a2b4cc3d --wallet 0:0ed725f5b27732c8e76adaabf7be36fd716d037ddf4ff872f462829dc9cf6c96 --keys /ton-node/configs/keys/msig.keys.json
Config: /ton-node/tools/tonos-cli.conf.json
Succeeded.
{
  "url": "\"https://rustnet.ton.dev\"",
  "wc": 0,
  "addr": "0:878b80596139958f45b3ce3e75211c2620b568d203ce382e7baf8fa4a2b4cc3d",
  "wallet": "0:0ed725f5b27732c8e76adaabf7be36fd716d037ddf4ff872f462829dc9cf6c96",
  "abi_path": null,
  "keys_path": "/ton-node/configs/keys/msig.keys.json",
  "retries": 5,
  "timeout": 60000,
  "is_json": false,
  "depool_fee": 0.5
}
+ '[' yes = yes ']'
+ echo 'DEBUG: /ton-node/tools/tonos-cli.conf.json BEGIN'
DEBUG: /ton-node/tools/tonos-cli.conf.json BEGIN
+ cat /ton-node/tools/tonos-cli.conf.json
{"url":"\"https://rustnet.ton.dev\"","wc":0,"addr":"0:878b80596139958f45b3ce3e75211c2620b568d203ce382e7baf8fa4a2b4cc3d","wallet":"0:0ed725f5b27732c8e76adaabf7be36fd716d037ddf4ff872f462829dc9cf6c96","abi_path":null,"keys_path":"/ton-node/configs/keys/msig.keys.json","retries":5,"timeout":60000,"is_json":false,"depool_fee":0.5}+ echo 'DEBUG: /ton-node/tools/tonos-cli.conf.json END'
DEBUG: /ton-node/tools/tonos-cli.conf.json END
++ jq .retries /ton-node/tools/tonos-cli.conf.json
+ '[' 5 '!=' 5 ']'
+ '[' yes '!=' yes ']'
+ prepare_for_elections
+ case ${ELECTOR_TYPE} in
++ /ton-node/tools/tonos-cli run -1:3333333333333333333333333333333333333333333333333333333333333333 active_election_id '{}' --abi /ton-node/configs/Elector.abi.json
++ grep value0
++ awk '{print $2}'
++ tr -d '"'
thread 'main' panicked at 'a parsed Url should always be a valid Uri: InvalidUri(InvalidUriChar)', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.10/src/into_url.rs:42:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
+++ exit_and_clean 1 238
+++ EXIT_CODE=1
+++ EXIT_LINE=238
+++ rm -f /tmp/validator.lock
+++ '[' 1 -eq 0 ']'
+++ echo 'INFO: script exited (exit code: 1, script line: 238)'

**Comment by stakrspace** [comment]
cat tonos-cli.conf.json
{"url":"https://rustnet.ton.dev","wc":0,"addr":"0:878b80596139958f45b3ce3e75211c2620b568d203ce382e7baf8fa4a2b4cc3d","wallet":"0:0ed725f5b27732c8e76adaabf7be36fd716d037ddf4ff872f462829dc9cf6c96","abi_path":null,"keys_path":"/ton-node/configs/keys/msig.keys.json","retries":5,"timeout":60000,"is_json":false,"depool_fee":0.5}

**Comment by ar-tmp** [comment]
Could you please try to renew https://github.com/tonlabs/rustnet.ton.dev/blob/main/docker-compose/ton-node/.env and restart the docker container (or re-deploy the node)?

**Comment by stakrspace** [comment]
Thanks, it works.
